//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentDetail
    {
        public int ID { get; set; }
        public int cust_Id { get; set; }
        public Nullable<decimal> balanceAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string received { get; set; }
        public string remark { get; set; }
        public string createdBy { get; set; }
        public byte[] signature { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
