//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CustomerDetail
    {
        public CustomerDetail()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
            this.CustomerCylinderDetails = new HashSet<CustomerCylinderDetail>();
            this.CustomerPaymentDetails = new HashSet<CustomerPaymentDetail>();
        }

        [Required(ErrorMessage = "please enter company name")]
        public string companyName { get; set; }
        [Required(ErrorMessage = "please enter address")]
        public string address { get; set; }
        [Required(ErrorMessage = "please enter primary contact")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "please enter valid phone number")]
        public string contact_Num_1 { get; set; }
        public string contact_Num_2 { get; set; }
        public string email { get; set; }
        public string gst { get; set; }
        public string discount { get; set; }
        public int cust_id { get; set; }
        public Nullable<decimal> openingBalance { get; set; }
        public Nullable<decimal> balanceAmount { get; set; }
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<CustomerCylinderDetail> CustomerCylinderDetail { get; set; }
        public IEnumerable<CustomerCylinderDetail> CustomerCylinderDetailForEdit { get; set; }
      
    
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
        public virtual ICollection<CustomerCylinderDetail> CustomerCylinderDetails { get; set; }
        public virtual ICollection<CustomerPaymentDetail> CustomerPaymentDetails { get; set; }
    }
}
