//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCylinderDetail
    {
        public int ID { get; set; }
        public string cylinderType { get; set; }
        public Nullable<int> totalCylinder { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string discount { get; set; }
        public Nullable<int> cylinder_Id { get; set; }
        public Nullable<int> openingCylinder { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual CylinderMaster CylinderMaster { get; set; }
    }
}
