//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CylinderMaster
    {
        public CylinderMaster()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.ReturnDetails = new HashSet<ReturnDetail>();
            this.LoadDetails = new HashSet<LoadDetail>();
            this.UnloadDetails = new HashSet<UnloadDetail>();
            this.CustomerCylinderDetails = new HashSet<CustomerCylinderDetail>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Please Enter Cylinder Type Name")]
        public string cylinderType { get; set; }
        [Required(ErrorMessage = "Please Enter Cylinder Amount")]
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> openingFilled { get; set; }
        public Nullable<int> openingEmpty { get; set; }
        public Nullable<int> openingReplace { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
        public virtual ICollection<LoadDetail> LoadDetails { get; set; }
        public virtual ICollection<UnloadDetail> UnloadDetails { get; set; }
        public virtual ICollection<CustomerCylinderDetail> CustomerCylinderDetails { get; set; }
    }
}
