//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DeliveryDetail
    {
        [Required(ErrorMessage = "please select date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime C_deliveryDate { get; set; }
        [Required(ErrorMessage = "please Enter voucher number")]
        public string voucherNo { get; set; }
        public Nullable<decimal> cylinderAmount { get; set; }
        public Nullable<int> filledCylinder { get; set; }
        public Nullable<int> emptyCylinder { get; set; }
        public decimal totalAmount { get; set; }
        public decimal paidAmount { get; set; }
        public Nullable<decimal> balanceAmount { get; set; }
        [Required(ErrorMessage = "please select customer")]
        public int cust_id { get; set; }
        [Required(ErrorMessage = "please select cylinder")]
        public int cylinder_Id { get; set; }
        public int ID { get; set; }
        public string Custsignature { get; set; }
        public string phone { get; set; }
        public byte[] signature { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<decimal> cgst { get; set; }
        public Nullable<decimal> sgst { get; set; }
        public string username { get; set; }
        public bool invoiceCheck { get; set; }

        public Nullable<int> replacementCylinder { get; set; }
        public Nullable<bool> unload_Flag { get; set; }
        public IEnumerable<tbluser> users;
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<CustomerDetail> customers { get; set; }
     
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual CylinderMaster CylinderMaster { get; set; }
        public virtual tbluser tbluser { get; set; }
    }
}
