//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveCylinderDetail
    {
        public int ID { get; set; }
        public Nullable<int> cylinder_Id { get; set; }
        public Nullable<int> FilledCylinderCount { get; set; }
        public Nullable<int> EmptyCylinderCount { get; set; }
        public Nullable<int> ReplacementCylinderCount { get; set; }
    }
}
