//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoadCylinder
    {
        public LoadCylinder()
        {
            this.LoadDetails = new HashSet<LoadDetail>();
        }

        [Required(ErrorMessage = "please select load date")]
        public Nullable<System.DateTime> loadDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        [Required(ErrorMessage = "please select User")]
        public int user_id { get; set; }
        public int ID { get; set; }
        public string userName { get; set; }
        public IEnumerable<tbluser> users;
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<LoadDetail> LoadDetail { get; set; }
        public IEnumerable<LoadDetail> LoadDetailForEdit { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<LoadDetail> LoadDetails { get; set; }
    }
}
