//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PurchaseCylinder
    {
        public PurchaseCylinder()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "please select dealer")]
        public string dealerName { get; set; }
        [Required(ErrorMessage = "please select purchase date")]
        [DataType(DataType.Date),DisplayFormat(DataFormatString="{0:dd/MM/yyyy}",ApplyFormatInEditMode=true)]
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<PurchaseDetail> PurchaseDetail { get; set; }
        public IEnumerable<PurchaseDetail> PurchaseDetailForEdit { get; set; }
        [Required(ErrorMessage = "please select dealer")]
        public string BillNo { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
