//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ReturnCylinder
    {
        public ReturnCylinder()
        {
            this.ReturnDetails = new HashSet<ReturnDetail>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "please select dealer")]
        public string dealerName { get; set; }
        public Nullable<int> emptyCylinder { get; set; }
        [Required(ErrorMessage = "please select return date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> returnDate { get; set; }
        public string ERVNo { get; set; }
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<ReturnDetail> ReturnDetail { get; set; }
        public IEnumerable<ReturnDetail> ReturnDetailForEdit { get; set; }

        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
    }
}
