//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDetail
    {
        public int ID { get; set; }
        public string cylinderType { get; set; }
        public Nullable<int> cylinder_Id { get; set; }
        public Nullable<int> return_Id { get; set; }
        public Nullable<int> FilledCylinder { get; set; }
        public Nullable<int> EmptyCylinder { get; set; }
        public Nullable<int> RejectedCylinder { get; set; }
    
        public virtual CylinderMaster CylinderMaster { get; set; }
        public virtual ReturnCylinder ReturnCylinder { get; set; }
    }
}
