//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbluser
    {
        public tbluser()
        {
            this.LoadCylinders = new HashSet<LoadCylinder>();
            this.UnloadCylinders = new HashSet<UnloadCylinder>();
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
            this.StaffPayments = new HashSet<StaffPayment>();
        }




        public int ID { get; set; }
        [Required(ErrorMessage = "please enter first name")]
        public string firstname { get; set; }
        [Required(ErrorMessage = "please enter last name")]
        public string lastname { get; set; }
        [Required(ErrorMessage = "please select user name")]
        public string username { get; set; }
        public string passwordHash { get; set; }
        public Nullable<System.Guid> salt { get; set; }
        public Nullable<int> role_id { get; set; }
        public IEnumerable<tblrole> roles { get; set; }
        public string phone { get; set; }
        public bool isActive { get; set; }

        

      
    
        public virtual ICollection<LoadCylinder> LoadCylinders { get; set; }
        public virtual ICollection<UnloadCylinder> UnloadCylinders { get; set; }
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
        public virtual ICollection<StaffPayment> StaffPayments { get; set; }

    }
}
