//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySaleDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UnloadCylinder
    {
        public UnloadCylinder()
        {
            this.UnloadDetails = new HashSet<UnloadDetail>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "please enter no. of empty cylinder")]
        public int EmptyCylinder { get; set; }
        [Required(ErrorMessage = "please select Unload date")]
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        [Required(ErrorMessage = "please select user")]
        public int user_id { get; set; }
        public string userName { get; set; }
        public Nullable<bool> DeliveryFlag { get; set; }
        public IEnumerable<tbluser> users;
        public IEnumerable<CylinderMaster> cylinders { get; set; }
        public IEnumerable<UnloadDetail> UnloadDetail { get; set; }
        public IEnumerable<UnloadDetail> UnloadDetailForEdit { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<UnloadDetail> UnloadDetails { get; set; }
    }
}
